{
 "title": "Beaconmetrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Current Blockchain Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blochain Infos",
   "type": "table",
   "description": "Some information about the blockchain",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(validator_status_info) by (environment, current_epoch,current_finalized_epoch,status,current_slot)"
    }
   ]
  },
  { "title": "Performance & Ranking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Rank 7 days sliding",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 6 },
   "targets": [
    { "expr": "validator_rank", "legendFormat": "Rank 7d" }
   ]
  },
  {
   "title": "Rewards / Penalty",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 9 },
   "targets": [
    { "expr": "validator_reward", "legendFormat": "Reward {{type}}" },
    { "expr": "validator_penalty * -1", "legendFormat": "Penalty {{type}}" }
   ]
  },
  {
   "title": "Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "validator_effectiveness", "legendFormat": "{{environment}}" }
   ]
  },
  {
   "title": "Daily Performance",
   "type": "timeseries",
   "description": "Sliding period",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "validator_performance{range=\"1d\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Weekly Performance",
   "type": "timeseries",
   "description": "Sliding period",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "validator_performance{range=\"7d\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Monthly Performance",
   "type": "timeseries",
   "description": "Sliding period",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "validator_performance{range=\"31d\"}",
     "legendFormat": "{{range}}"
    }
   ]
  }
 ]
}